// <auto-generated />
using System;
using Catalog.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.DataAccess.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20221229231514_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Core.Models.CatalogBrand", b =>
                {
                    b.Property<int>("CatalogBrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatalogBrandID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("date");

                    b.HasKey("CatalogBrandID");

                    b.ToTable("CatalogBrands", "Catalog");

                    b.HasData(
                        new
                        {
                            CatalogBrandID = 1,
                            Brand = "N/A",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(2607),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(3262)
                        },
                        new
                        {
                            CatalogBrandID = 2,
                            Brand = "Coca-Cola",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(3885),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(4489)
                        },
                        new
                        {
                            CatalogBrandID = 3,
                            Brand = "Terrabusi",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(5113),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(5732)
                        },
                        new
                        {
                            CatalogBrandID = 4,
                            Brand = "Marlboro",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(6352),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(6959)
                        },
                        new
                        {
                            CatalogBrandID = 5,
                            Brand = "Quilmes",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(7582),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 415, DateTimeKind.Local).AddTicks(8189)
                        });
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogItem", b =>
                {
                    b.Property<int>("CatalogItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatalogItemID"));

                    b.Property<int>("AvailableStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CatalogBrandID")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaxStockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("OnReorder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PictureFileName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("placeholder.png");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("RestockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("date");

                    b.HasKey("CatalogItemID");

                    b.HasIndex("CatalogBrandID");

                    b.HasIndex("CatalogTypeID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CatalogItems", "Catalog");

                    b.HasData(
                        new
                        {
                            CatalogItemID = 1,
                            AvailableStock = 0,
                            CatalogBrandID = 2,
                            CatalogTypeID = 2,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 416, DateTimeKind.Local).AddTicks(3660),
                            Description = "",
                            MaxStockThreshold = 1,
                            Name = "Sin Azúcar 1.5l",
                            OnReorder = false,
                            PictureFileName = "placeholder.png",
                            Price = 0m,
                            RestockThreshold = 0,
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 416, DateTimeKind.Local).AddTicks(4299)
                        },
                        new
                        {
                            CatalogItemID = 2,
                            AvailableStock = 0,
                            CatalogBrandID = 5,
                            CatalogTypeID = 5,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 416, DateTimeKind.Local).AddTicks(4932),
                            Description = "",
                            MaxStockThreshold = 1,
                            Name = "Clásica 500ml",
                            OnReorder = false,
                            PictureFileName = "placeholder.png",
                            Price = 0m,
                            RestockThreshold = 0,
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 416, DateTimeKind.Local).AddTicks(5545)
                        },
                        new
                        {
                            CatalogItemID = 3,
                            AvailableStock = 0,
                            CatalogBrandID = 3,
                            CatalogTypeID = 4,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 416, DateTimeKind.Local).AddTicks(6171),
                            Description = "",
                            MaxStockThreshold = 1,
                            Name = "Tita",
                            OnReorder = false,
                            PictureFileName = "placeholder.png",
                            Price = 0m,
                            RestockThreshold = 0,
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 416, DateTimeKind.Local).AddTicks(6795)
                        },
                        new
                        {
                            CatalogItemID = 4,
                            AvailableStock = 0,
                            CatalogBrandID = 4,
                            CatalogTypeID = 3,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 416, DateTimeKind.Local).AddTicks(7421),
                            Description = "",
                            MaxStockThreshold = 1,
                            Name = "Ice Blast 8",
                            OnReorder = false,
                            PictureFileName = "placeholder.png",
                            Price = 0m,
                            RestockThreshold = 0,
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 416, DateTimeKind.Local).AddTicks(8031)
                        });
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogType", b =>
                {
                    b.Property<int>("CatalogTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatalogTypeID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("date");

                    b.HasKey("CatalogTypeID");

                    b.ToTable("CatalogTypes", "Catalog");

                    b.HasData(
                        new
                        {
                            CatalogTypeID = 1,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 416, DateTimeKind.Local).AddTicks(9958),
                            Type = "N/A",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 417, DateTimeKind.Local).AddTicks(581)
                        },
                        new
                        {
                            CatalogTypeID = 2,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 417, DateTimeKind.Local).AddTicks(1210),
                            Type = "Gaseosas",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 417, DateTimeKind.Local).AddTicks(1823)
                        },
                        new
                        {
                            CatalogTypeID = 3,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 417, DateTimeKind.Local).AddTicks(2445),
                            Type = "Cigarrillos",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 417, DateTimeKind.Local).AddTicks(3051)
                        },
                        new
                        {
                            CatalogTypeID = 4,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 417, DateTimeKind.Local).AddTicks(3672),
                            Type = "Alfajores & Obleas",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 417, DateTimeKind.Local).AddTicks(4280)
                        },
                        new
                        {
                            CatalogTypeID = 5,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 417, DateTimeKind.Local).AddTicks(4895),
                            Type = "Cervezas",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2022, 12, 29, 20, 15, 14, 417, DateTimeKind.Local).AddTicks(5503)
                        });
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogItem", b =>
                {
                    b.HasOne("Catalog.Core.Models.CatalogBrand", "CatalogBrand")
                        .WithMany("CatalogItems")
                        .HasForeignKey("CatalogBrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.Core.Models.CatalogType", "CatalogType")
                        .WithMany("CatalogItems")
                        .HasForeignKey("CatalogTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogBrand");

                    b.Navigation("CatalogType");
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogBrand", b =>
                {
                    b.Navigation("CatalogItems");
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogType", b =>
                {
                    b.Navigation("CatalogItems");
                });
#pragma warning restore 612, 618
        }
    }
}
