// <auto-generated />
using System;
using Catalog.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.DataAccess.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Core.Models.CatalogBrand", b =>
                {
                    b.Property<int>("CatalogBrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatalogBrandID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("date");

                    b.HasKey("CatalogBrandID");

                    b.ToTable("CatalogBrands", "Catalog");

                    b.HasData(
                        new
                        {
                            CatalogBrandID = 1,
                            Brand = "N/A",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 442, DateTimeKind.Local).AddTicks(6636),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 442, DateTimeKind.Local).AddTicks(7280)
                        },
                        new
                        {
                            CatalogBrandID = 2,
                            Brand = "Coca-Cola",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 442, DateTimeKind.Local).AddTicks(7917),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 442, DateTimeKind.Local).AddTicks(8524)
                        },
                        new
                        {
                            CatalogBrandID = 3,
                            Brand = "Terrabusi",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 442, DateTimeKind.Local).AddTicks(9144),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 442, DateTimeKind.Local).AddTicks(9718)
                        },
                        new
                        {
                            CatalogBrandID = 4,
                            Brand = "Marlboro",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 443, DateTimeKind.Local).AddTicks(260),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 443, DateTimeKind.Local).AddTicks(855)
                        },
                        new
                        {
                            CatalogBrandID = 5,
                            Brand = "Quilmes",
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 443, DateTimeKind.Local).AddTicks(1463),
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 443, DateTimeKind.Local).AddTicks(2064)
                        });
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogItem", b =>
                {
                    b.Property<int>("CatalogItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatalogItemID"));

                    b.Property<int>("AvailableStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CatalogBrandID")
                        .HasColumnType("int");

                    b.Property<int>("CatalogTypeID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxStockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("OnReorder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PictureFileName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("placeholder.png");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("date");

                    b.HasKey("CatalogItemID");

                    b.HasIndex("CatalogBrandID");

                    b.HasIndex("CatalogTypeID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CatalogItems", "Catalog");

                    b.HasData(
                        new
                        {
                            CatalogItemID = 1,
                            AvailableStock = 0,
                            CatalogBrandID = 2,
                            CatalogTypeID = 2,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 443, DateTimeKind.Local).AddTicks(8389),
                            Description = "",
                            MaxStockThreshold = 1,
                            Name = "Sin Azúcar 1.5l",
                            OnReorder = false,
                            PictureFileName = "placeholder.png",
                            Price = 0m,
                            RestockThreshold = 0,
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 443, DateTimeKind.Local).AddTicks(8999)
                        },
                        new
                        {
                            CatalogItemID = 2,
                            AvailableStock = 0,
                            CatalogBrandID = 5,
                            CatalogTypeID = 5,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 443, DateTimeKind.Local).AddTicks(9612),
                            Description = "",
                            MaxStockThreshold = 1,
                            Name = "Clásica 500ml",
                            OnReorder = false,
                            PictureFileName = "placeholder.png",
                            Price = 0m,
                            RestockThreshold = 0,
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(217)
                        },
                        new
                        {
                            CatalogItemID = 3,
                            AvailableStock = 0,
                            CatalogBrandID = 3,
                            CatalogTypeID = 4,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(816),
                            Description = "",
                            MaxStockThreshold = 1,
                            Name = "Tita",
                            OnReorder = false,
                            PictureFileName = "placeholder.png",
                            Price = 0m,
                            RestockThreshold = 0,
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(1410)
                        },
                        new
                        {
                            CatalogItemID = 4,
                            AvailableStock = 0,
                            CatalogBrandID = 4,
                            CatalogTypeID = 3,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(1999),
                            Description = "",
                            MaxStockThreshold = 1,
                            Name = "Ice Blast 8",
                            OnReorder = false,
                            PictureFileName = "placeholder.png",
                            Price = 0m,
                            RestockThreshold = 0,
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(2597)
                        });
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogType", b =>
                {
                    b.Property<int>("CatalogTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatalogTypeID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("date");

                    b.HasKey("CatalogTypeID");

                    b.ToTable("CatalogTypes", "Catalog");

                    b.HasData(
                        new
                        {
                            CatalogTypeID = 1,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(4604),
                            Type = "N/A",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(5216)
                        },
                        new
                        {
                            CatalogTypeID = 2,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(5824),
                            Type = "Gaseosas",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(6427)
                        },
                        new
                        {
                            CatalogTypeID = 3,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(7023),
                            Type = "Cigarrillos",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(7618)
                        },
                        new
                        {
                            CatalogTypeID = 4,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(8212),
                            Type = "Alfajores & Obleas",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(8806)
                        },
                        new
                        {
                            CatalogTypeID = 5,
                            CreatedBy = "Fedex",
                            CreatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(9401),
                            Type = "Cervezas",
                            UpdatedBy = "Fedex",
                            UpdatedOn = new DateTime(2023, 2, 10, 18, 9, 6, 444, DateTimeKind.Local).AddTicks(9993)
                        });
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogItem", b =>
                {
                    b.HasOne("Catalog.Core.Models.CatalogBrand", "CatalogBrand")
                        .WithMany("CatalogItems")
                        .HasForeignKey("CatalogBrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.Core.Models.CatalogType", "CatalogType")
                        .WithMany("CatalogItems")
                        .HasForeignKey("CatalogTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogBrand");

                    b.Navigation("CatalogType");
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogBrand", b =>
                {
                    b.Navigation("CatalogItems");
                });

            modelBuilder.Entity("Catalog.Core.Models.CatalogType", b =>
                {
                    b.Navigation("CatalogItems");
                });
#pragma warning restore 612, 618
        }
    }
}
